Update setup.py
File "/home/kali/Downloads/Pyrit/setup.py", line 56
    print "Failed to build; Compiling without AES-NI"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?